module.exports.EVENT_CONSTANT = {
  START_FLOW: 0,
  AFTER_FIRST_PROCESS: 1,
  SEND_TO_MASTER: 2,
  BUILD_FAKE: 3,
  ADDED_TO_QUEUE: 4,
  DO_SEND: 5,
  FINISH_SEND: 6,
  COMMIT_REQUEST: 7,

  START_EXECUTE: 100,
  CREATE_COMMIT: 101,
  PERFECT_FORM: 102,

  REQUIRE_SYNC: 199,
  EXEC_BULK: 200,
  DO_BULK_QUERY: 201,
  BULK_ERROR: 202,
  CREATE_COMMIT_CLIENT: 203,
  FLOW_EXEC: 204,
  FLOW_SHOULD_NOT_EXEC: 205,
  FLOW_EXEC_ERROR: 206
}
